import Foundation
import InputInformationFeatureInterface
import MainFeatureInterface
import SigninFeatureInterface
import SplashFeatureInterface
import MyPageFeatureInterface

protocol RootIntentProtocol: InputInformationDelegate, SigninDelegate, MainDelegate, SplashDelegate, MyPageDelegate {}
