import Foundation
import InputInformationFeatureInterface
import SigninFeatureInterface
import FilterFeatureInterface

protocol RootIntentProtocol: InputInformationDelegate, SigninDelegate, FilterDelegate {}
