import Foundation
import InputInformationFeatureInterface
import MainFeatureInterface
import SigninFeatureInterface
import SplashFeatureInterface

protocol RootIntentProtocol: InputInformationDelegate, SigninDelegate, MainDelegate, SplashDelegate {}
