# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "distribute app"
  lane :release do |options|
    version = options[:version]

    build_number = get_info_plist_value(path: "./Projects/App/Support/Info.plist", key: "CFBundleVersion")
    set_info_plist_value(path: "./Projects/App/Support/Info.plist", key: "CFBundleVersion", value: "#{build_number.to_i + 1}")
    set_info_plist_value(path: "./Projects/App/Support/Info.plist", key: "CFBundleShortVersionString", value: version)
    xcversion(version: "13.3.1")

    build_app(
        scheme: "SMS-PROD",
        export_method: "app-store",
        export_options: {
            "com.msg.SMS-iOS": "SMS_CD",
        },
        export_team_id: ENV["TEAM_ID"]
    )

    upload_to_app_store(
        app_version: version,
        force: true,
        submit_for_review: true,
        automatic_release: true,
        api_key_path: "fastlane/SMS-AppStoreAPIKey.json",
        precheck_include_in_app_purchases: false,
        submission_information: {
            add_id_info_uses_idfa: false
        }
    )

    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "🚀 SMS iOS 배포 자동화 성공",
      thumbnail_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Test-Logo.svg/1566px-Test-Logo.svg.png?20150906031702",
      description: "SMS iOS #{version}을 앱스토어에 성공적으로 배포하였습니다 !"
    )
    # add actions here: https://docs.fastlane.tools/actions
  end

  error do |lane, exception, options|
    log = sh("cat /Users/runner/Library/Logs/gym/SMS-SMS-PROD.log")

    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "👾 SMS iOS 배포 자동화 실패..",
      thumbnail_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Test-Logo.svg/1566px-Test-Logo.svg.png?20150906031702",
      success: false,
      color: "#BB3639",
      description: "#{exception}\n #{log}"
    )
  end
end
