name: SMS-IOS-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/Tuist/Dependencies

jobs:
  prepare-dependency:
    name: CI
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tuist
      run: curl -Ls https://install.tuist.io | bash

    - name: Check dependency cache
      uses: actions/cache@v3
      id: cache_dependencies
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: ${{ steps.compute_hash.outputs.hash }}

    - name: Install dependencies
      if: steps.cache_dependencies.outputs.cache-hit == ''
      run: tuist fetch

    - name: Test with tuist
      run: TUIST_CI=1 tuist test
